# Generated by Django 5.2.7 on 2025-11-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_task_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status", "due_date"],
                name="task_proj_status_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__isnull", True),
                    ("due_date__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="task_due_after_created",
            ),
        ),
    ]
