# Generated by Django 5.2.7 on 2025-11-06 13:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_trigram_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="task_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
